import { useEffect } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";
import { ArrowLeft } from "lucide-react";
import { useData } from "../../lib/store";
import { Card } from "../../components/ui/card";
import { Button } from "../../components/ui/button";
import { PageHeader } from "../../components/page-header";
import { formatFullNaira } from "../../lib/format";
import { useAuth } from "../../context/AuthContext";

const moneyFields = new Set([
  "productionValue",
  "rawMaterialsCost",
  "rawMaterialsTransport",
  "unsoldGoods",
  "investLandBuildings",
  "investPlant",
  "investFurniture",
  "investVehicles",
  "investInProgress",
  "energyDiesel",
  "energyGas",
  "energyGenerator",
  "energyOther",
]);

const sections = [
  {
    title: "Core indices",
    fields: [
      "capacityUtilization",
      "productionValue",
      "rawMaterialsCost",
      "rawMaterialsTransport",
      "localSourcing",
      "unsoldGoods",
      "newHires",
      "totalWorkers",
      "workersLeft",
    ],
  },
  {
    title: "Investment",
    fields: [
      "investLandBuildings",
      "investPlant",
      "investFurniture",
      "investVehicles",
      "investInProgress",
      "interestRate",
      "exchangeRate",
    ],
  },
  {
    title: "Energy and power",
    fields: [
      "totalEnergyGenerated",
      "totalEnergyConsumed",
      "energyGeneratedByGas",
      "energyGeneratedByDiesel",
      "energyGeneratedByGenerator",
      "energyGeneratedByOther",
      "electricityHours",
      "powerOutages",
      "energyDiesel",
      "energyGas",
      "energyGenerator",
      "energyOther",
    ],
  },
];

const labels: Record<string, string> = {
  capacityUtilization: "Capacity utilization",
  productionValue: "Production value",
  rawMaterialsCost: "Raw materials cost",
  rawMaterialsTransport: "Raw materials transport",
  localSourcing: "Local sourcing",
  unsoldGoods: "Unsold goods",
  newHires: "New hires",
  totalWorkers: "Total workers",
  workersLeft: "Workers left",
  investLandBuildings: "Land and buildings",
  investPlant: "Plant and machinery",
  investFurniture: "Furniture",
  investVehicles: "Motor vehicles",
  investInProgress: "Assets in progress",
  interestRate: "Interest rate",
  exchangeRate: "Exchange rate",
  totalEnergyGenerated: "Total energy generated",
  totalEnergyConsumed: "Total energy consumed",
  energyGeneratedByGas: "Energy generated by gas",
  energyGeneratedByDiesel: "Energy generated by diesel",
  energyGeneratedByGenerator: "Energy generated by generator",
  energyGeneratedByOther: "Energy generated by other sources",
  electricityHours: "Average grid hours",
  powerOutages: "Average power outages",
  energyDiesel: "Diesel energy cost",
  energyGas: "Gas energy cost",
  energyGenerator: "Generator maintenance cost",
  energyOther: "Other energy cost",
};

function displayValue(field: string, value: unknown) {
  if (typeof value !== "number") return "-";
  if (moneyFields.has(field)) return formatFullNaira(value);
  if (
    field === "capacityUtilization" ||
    field === "localSourcing" ||
    field === "interestRate"
  )
    return `${value}%`;
  return value.toLocaleString();
}

export function SubmissionDetailPage() {
  const { id } = useParams();
  const navigate = useNavigate();
  const { user } = useAuth();
  const {
    manufacturers,
    questionnaires,
    fetchManufacturers,
    fetchQuestionnaires,
  } = useData();
  const candidate = questionnaires.find((item) => String(item.id) === id);
  const owner = manufacturers.find(
    (item) => item.manId === candidate?.manufacturerId,
  );
  const canView =
    user?.role === "admin" ||
    owner?.email.toLowerCase() === user?.email.toLowerCase();
  const submission = canView ? candidate : undefined;
  const manufacturer = manufacturers.find(
    (item) => item.manId === submission?.manufacturerId,
  );

  useEffect(() => {
    void fetchManufacturers();
    void fetchQuestionnaires();
  }, [fetchManufacturers, fetchQuestionnaires]);

  if (!submission) {
    return (
      <div className="p-6 lg:p-10">
        <PageHeader
          title="Submission not found"
          subtitle="This submission may have been removed."
        />
        <Button asChild variant="outline">
          <Link to="/submissions">Back to submissions</Link>
        </Button>
      </div>
    );
  }

  return (
    <div className="p-6 lg:p-10 space-y-6 max-w-[1200px]">
      <Button variant="ghost" onClick={() => navigate("/submissions")}>
        <ArrowLeft className="w-4 h-4 mr-2" /> Back to submissions
      </Button>
      <PageHeader
        title={manufacturer?.name ?? "Company submission"}
        subtitle={`${submission.period} submission summary`}
      />
      <Card className="p-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <SummaryItem label="Status" value={submission.status ?? "submitted"} />
        <SummaryItem label="Period" value={submission.period} />
        <SummaryItem
          label="Start date"
          value={submission.startTime.toLocaleDateString()}
        />
        <SummaryItem
          label="Submitted by"
          value={submission.submittedBy || "-"}
        />
      </Card>
      {sections.map((section) => (
        <Card key={section.title} className="p-6 space-y-4">
          <h2 className="font-display font-semibold">{section.title}</h2>
          <div className="grid gap-x-8 gap-y-4 sm:grid-cols-2 lg:grid-cols-3">
            {section.fields.map((field) => (
              <SummaryItem
                key={field}
                label={labels[field]}
                value={displayValue(
                  field,
                  submission[field as keyof typeof submission],
                )}
              />
            ))}
          </div>
        </Card>
      ))}
      <Card className="p-6 space-y-2">
        <h2 className="font-display font-semibold">Nigeria First comment</h2>
        <p className="text-sm text-muted-foreground whitespace-pre-wrap">
          {submission.nigeriaFirstComment || "No comment provided."}
        </p>
      </Card>
    </div>
  );
}

function SummaryItem({ label, value }: { label: string; value: string }) {
  return (
    <div>
      <div className="text-xs text-muted-foreground">{label}</div>
      <div className="font-medium mt-1">{value}</div>
    </div>
  );
}
